### ISSUE TITLE
钉钉红包

### ISSUE THREAD

**Issue by JauYang** [1izheng/Xpage#2]
大佬，有钉钉红包下单接口吗？

`service="alipay.fund.stdtrustee.order.create.pay"&partner="2088801132166875"&_input_charset="utf-8"&notify_url="https://repay.dingtalk.com/RENotify/alipay_fund_stdtrustee_order_create_pay"&out_order_no="htFgSdKY_622871412100"&out_request_no="htFgSdKY_622871412100_s"&product_code="SOCIAL_RED_PACKETS"&scene_code="MERCHANT_COUPON"&amount="0.05"&pay_strategy="CASHIER_PAYMENT"&receipt_strategy="INNER_ACCOUNT_RECEIPTS"&platform="DEFAULT"&channel="APP"&order_title="发送钉钉红包"&master_order_no="2019031310002001290265919826"&order_type="DEDUCT_ORDER"&extra_param="{"payeeShowName":"钉钉红包"}"&pay_timeout="30m"&order_expired_time="60d"&out_context="{"dingtalk_biz_tag":"red_envelop"}"&sign="Wcx%2B9AsfkAcZ0nkRfffZQubN8IG5%2FaikOulRxWpY7btqdPbKGMTzLDtpps%2FLUMhC4M1%2Fxhvpa%2Br96uGihXrNmOIIvMych%2FOOXyADjbSjs2VxZRhlUEzUNejfSA8RoEBxIq91Gjs0dYHmXIkDIJDEwLED7xSnnh9MznJpfj8ixzyDm9un%2Bfy1PZhl1q1%2F047Z8FgU%2Bs98%2FOcdJO%2BIfcG38jQt6Y%2Fm0xTHCu628Btn6ovlB0f1jhFflzfztZKvxe5f%2FNCDgyqOdA9h2jvSvbg%2BA%2FyA11Eh7gc8OJ1BMHt7blHCh%2Bpij%2F%2F11bhB3LhwC4mXGYPhkP1QB31CmGRRdtouLw%3D%3D"&sign_type="RSA"`

**Comment by 1izheng** [comment]
> 大佬，有钉钉红包下单接口吗？
> 
> `service="alipay.fund.stdtrustee.order.create.pay"&partner="2088801132166875"&_input_charset="utf-8"&notify_url="https://repay.dingtalk.com/RENotify/alipay_fund_stdtrustee_order_create_pay"&out_order_no="htFgSdKY_622871412100"&out_request_no="htFgSdKY_622871412100_s"&product_code="SOCIAL_RED_PACKETS"&scene_code="MERCHANT_COUPON"&amount="0.05"&pay_strategy="CASHIER_PAYMENT"&receipt_strategy="INNER_ACCOUNT_RECEIPTS"&platform="DEFAULT"&channel="APP"&order_title="发送钉钉红包"&master_order_no="2019031310002001290265919826"&order_type="DEDUCT_ORDER"&extra_param="{"payeeShowName":"钉钉红包"}"&pay_timeout="30m"&order_expired_time="60d"&out_context="{"dingtalk_biz_tag":"red_envelop"}"&sign="Wcx%2B9AsfkAcZ0nkRfffZQubN8IG5%2FaikOulRxWpY7btqdPbKGMTzLDtpps%2FLUMhC4M1%2Fxhvpa%2Br96uGihXrNmOIIvMych%2FOOXyADjbSjs2VxZRhlUEzUNejfSA8RoEBxIq91Gjs0dYHmXIkDIJDEwLED7xSnnh9MznJpfj8ixzyDm9un%2Bfy1PZhl1q1%2F047Z8FgU%2Bs98%2FOcdJO%2BIfcG38jQt6Y%2Fm0xTHCu628Btn6ovlB0f1jhFflzfztZKvxe5f%2FNCDgyqOdA9h2jvSvbg%2BA%2FyA11Eh7gc8OJ1BMHt7blHCh%2Bpij%2F%2F11bhB3LhwC4mXGYPhkP1QB31CmGRRdtouLw%3D%3D"&sign_type="RSA"`

额。 这个没的玩了吧

**Comment by JauYang** [comment]
可以加个联系方式吗，我也是同行技术

**Comment by 1izheng** [comment]
> 可以加个联系方式吗，我也是同行技术

你留吧 我加你

**Comment by JauYang** [comment]
Q:1079277561

**Comment by miclcx** [comment]
@1izheng 大佬可以加个Q吗  我也是同行  求方案：1336208558

**Comment by wangyhua** [comment]
淘宝红包还能用。同不知道下单接口。网上看了有人做了demo http://admin.php05.cn/pay，如果可以一起讨论的话加下qq 12732645
抓了下他的参数如下

service="alipay.fund.stdtrustee.order.create.pay"&partner="2088401309894080"&_input_charset="utf-8"&notify_url="https://wwhongbao.taobao.com/callback/alipay/notifyPaySuccess.do"&out_order_no="12621186_3189_1555058456_84fd53e39ac94c39b0f5d9d6a772a296_1"&out_request_no="12621186_3189_1555058456_84fd53e39ac94c39b0f5d9d6a772a296_1_p"&product_code="SOCIAL_RED_PACKETS"&scene_code="MERCHANT_COUPON"&amount="0.01"&pay_strategy="CASHIER_PAYMENT"&receipt_strategy="INNER_ACCOUNT_RECEIPTS"&platform="DEFAULT"&channel="APP"&order_title="淘宝现金红包"&master_order_no="2019041210002001290228940450"&order_type="DEDUCT_ORDER"&extra_param="{"payeeShowName":"淘宝现金红包"}"&pay_timeout="30m"&order_expired_time="360d"&sign="PmsEQPJDu8F%2FkiC0DvB0qpRtyVbmg3stDKTyidhm0lkZthMfIHARH1HwJUwnloXneon9xCm4foVJ8wrBCCerrV1DDw8gh2emgU4FqHF7yTcl3qAkmr9hWwoV66inTzcDAUb%2F%2F7LLfz0nkBKai3B8qH7ZyU6OJu3JG9j67cXIpdRkM6WxnpzJx%2FJLYduAT3QAsVh1DuNUv0dfKoVtgQECxcdb0cHj0QZbqHpP%2BXJ6z3w13qyJ5NzYd56MfHhYPoZhX7sjXILVgwNCo0Kmk6QhdFDRthUXnjTB9slnG1X0WuRbsEf1ttMs7IB2tKYskWfl4%2Bn5jvlavAi%2FrV%2Fc2a0y7g%3D%3D"&sign_type="RSA"

**Comment by Tokimekis** [comment]
还有大佬在吗？加个好友交流一下啊 Q 7740148

**Comment by huangliliu0917** [comment]
加个好友交流下，有偿请教。 Q:65665437
